input_path:
  gcs: 
      project: 'okcredit-data-science'
      bucket_name: 'okc_underwriting'
      input_data: 'model_retraining_pipeline/v1_1/input_data/'
      features: 'model_retraining_pipeline/v1_1/features/'

  local:
    base: './data'

    train:
      features:
        - 'train_tl_fts.csv'
        - 'train_bnpl_fts.csv'

      order: 'train_comb.csv'

    test:
      features:
        - 'test_tl_fts.csv'
        - 'test_bnpl_fts.csv'


column_profile:
    features: ['pred_labels',
    'range_tnx_hour_last_90_days',
    'range_tnx_hour_last_180_days',
    'range_tnx_hour_last_365_days',
    'range_tnx_hour_last_150_days',
    'range_tnx_hour_last_120_days',
    'range_tnx_hour_last_60_days',
    'pincode_2',
    'pincode_3',
    'state',
    'total_sessions_diff_3_to_7_days',
    'seller_min_amount_ratio_15_to_30_days',
    'total_sessions_last_90_days',
    'score',
    'std_tnx_hour_last_90_days',
    'total_sessions_diff_7_to_30_days',
    'seller_min_amount_diff_15_to_30_days',
    'total_sessions_last_3_days',
    'total_sessions_last_60_days',
    'avg_tnx_hour_last_60_days',
    'seller_unique_account_ids_ratio_3_to_7_days',
    'range_tnx_hour_last_45_days',
    'avg_tnx_hour_last_45_days',
    'std_tnx_hour_last_120_days',
    'avg_tnx_hour_last_180_days',
    'total_sessions_last_30_days',
    'avg_tnx_hour_last_30_days',
    'std_tnx_hour_last_150_days',
    'total_sessions_last_45_days',
    'buyer_total_transactions_diff_150_to_180_days',
    'avg_tnx_hour_last_150_days',
    'total_sessions_last_15_days',
    'seller_avg_amount_last_15_days',
    'avg_tnx_hour_last_365_days',
    'avg_tnx_hour_last_90_days',
    'total_sessions_last_7_days',
    'seller_avg_num_transactions_per_account_id_ratio_7_to_15_days',
    'total_sessions_diff_30_to_90_days',
    'std_tnx_hour_last_180_days',
    'avg_tnx_hour_last_7_days',
    'seller_range_amount_diff_180_to_365_days',
    'range_tnx_hour_last_7_days',
    'std_tnx_dayofweek_last_150_days',
    'total_sessions_diff_15_to_60_days',
    'std_tnx_dayofweek_last_7_days',
    'avg_tnx_hour_last_120_days',
    'seller_range_amount_ratio_180_to_365_days',
    'total_sessions_diff_7_to_90_days',
    'total_sessions_ratio_3_to_7_days',
    'seller_unique_account_ids_last_30_days']

    categorical: ['pred_labels', 'city', 'district', 'state']

    target: target

    sort_column: None


validation:
  class: BlockTimeSplit
  kwargs:
    n_splits: 9

model:
  class: RandomForestClassifier
  model_kwargs:
    min_samples_leaf: 8
    min_samples_split: 8
    max_depth: 3
    random_state: 19
    n_estimators: 400
    max_features: 0.2
    n_jobs: 8
    max_samples: 0.8


  fit_kwargs:
    early_stopping_rounds: 100
    eval_metric: auc
    verbose: 50

output_path:
  model:
    save_name: model.pkl
    local: './artifacts'
    gcs: 
      project: 'okcredit-data-science'
      bucket_name: 'okc_underwriting'
      folder_name: 'model_retraining_pipeline/v1_1/artifacts/'
  test_scores:
    save_name: 'test_scores.csv'
